name: Generate README.md from master branch
on:
  # Update on push to master or via schedule
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Check the syntax in https://crontab.guru/
    - cron: "0 0 * * *"

jobs:
  build:
    name: Generate README.md file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 # Full repo history
      - name: Read .nvmrc
        id: read_nvmrc
        run: |
          echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.read_nvmrc.outputs.NODE_VERSION }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install
      - name: Run generate_readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run generate_readme
      - name: Commit new files
        run: |
          # We use the e-mail mentioned here: https://github.community/t/github-actions-bot-email-address/17204/6

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions"
          git commit -a -m "Update README.md"
      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
